const ActionConstants = {
  GARDEN_ADD_FLOWER: "GARDEN_ADD_FLOWER",
  GARDEN_ADD_PLAYER: "GARDEN_ADD_PLAYER",
  GARDEN_ADD_CONNECTION: "GARDEN_ADD_CONNECTION",
  GARDEN_SET_HALF_CONNECTION: "GARDEN_SET_HALF_CONNECTION",
};

export default ActionConstants;
